"""Persistent task-main coordinator package (M3/W1).

Narrow durable Milestone activation / ready-evaluation / dispatch /
restart-recovery surface over the accepted M2 runtime. Execution working
truth only — never Plan authority.
"""

from aota_forge.runtime.task_main.coordinator import (
    COORDINATOR_DISPATCH_ATTEMPT,
    DAG_PROGRESSION_DETERMINISTIC,
    NEXT_MILESTONE_GUARD,
    PERSISTENCE_REQUIRES_FOREVER_PROCESS,
    SESSION_GATE_REASON,
    TASK_MAIN_CAN_CROSS_USER_GATE,
    TASK_MAIN_CAN_SET_USER_APPROVAL,
    TASK_MAIN_RAW_SHELL_REQUIRED,
    TASK_MAIN_UNRESTRICTED_FILESYSTEM_REQUIRED,
    USER_GATE_REASON,
    CoordinatorBindingError,
    CoordinatorRuntimeError,
    DispatchedWork,
    DispatchReport,
    MilestonePlanView,
    PlanDriftError,
    SessionRecoveryRequiredError,
    TaskMainCoordinator,
    TaskMainCoordinatorError,
    activate_milestone,
    build_work_item_handoff_ref,
    dispatch_identity_for,
    evaluate_ready_work_items,
    recover_coordinator,
)
from aota_forge.runtime.task_main.coordinator_state import (
    ACK_AFTER_SEMANTIC_RECONCILIATION_IMPLEMENTED,
    COORDINATOR_STATE_IS_PLAN_AUTHORITY,
    COORDINATOR_STATE_SCHEMA_VERSION,
    COORDINATOR_STATUSES,
    EXECUTION_STATE_STORE_USED_AS_COORDINATOR_STATE,
    HERMES_SESSION_DB_IS_COORDINATOR_AUTHORITY,
    MILESTONE_CLOSURE_AUTOMATION_IMPLEMENTED,
    REPAIR_AUTOMATION_IMPLEMENTED,
    REVIEW_AUTOMATION_IMPLEMENTED,
    W1_CARD_SEMANTIC_APPLICATION_IMPLEMENTED,
    WORK_ITEM_STATUSES,
    CoordinatorStatus,
    TaskMainCoordinatorState,
    WorkItemCoordinatorStatus,
)
from aota_forge.runtime.task_main.coordinator_store import (
    FILE_BACKED_IS_PRODUCTION_DEFAULT,
    PRODUCTION_COORDINATOR_STORE_FROZEN,
    CoordinatorIdempotencyConflictError,
    CoordinatorNotFoundError,
    CoordinatorPersistenceFailureError,
    FileBackedTaskMainCoordinatorStore,
    StaleCoordinatorRevisionError,
    TaskMainCoordinatorStore,
)

__all__ = [
    "ACK_AFTER_SEMANTIC_RECONCILIATION_IMPLEMENTED",
    "COORDINATOR_DISPATCH_ATTEMPT",
    "COORDINATOR_STATE_IS_PLAN_AUTHORITY",
    "COORDINATOR_STATE_SCHEMA_VERSION",
    "COORDINATOR_STATUSES",
    "DAG_PROGRESSION_DETERMINISTIC",
    "EXECUTION_STATE_STORE_USED_AS_COORDINATOR_STATE",
    "FILE_BACKED_IS_PRODUCTION_DEFAULT",
    "HERMES_SESSION_DB_IS_COORDINATOR_AUTHORITY",
    "MILESTONE_CLOSURE_AUTOMATION_IMPLEMENTED",
    "NEXT_MILESTONE_GUARD",
    "PERSISTENCE_REQUIRES_FOREVER_PROCESS",
    "PRODUCTION_COORDINATOR_STORE_FROZEN",
    "REPAIR_AUTOMATION_IMPLEMENTED",
    "REVIEW_AUTOMATION_IMPLEMENTED",
    "SESSION_GATE_REASON",
    "TASK_MAIN_CAN_CROSS_USER_GATE",
    "TASK_MAIN_CAN_SET_USER_APPROVAL",
    "TASK_MAIN_RAW_SHELL_REQUIRED",
    "TASK_MAIN_UNRESTRICTED_FILESYSTEM_REQUIRED",
    "USER_GATE_REASON",
    "W1_CARD_SEMANTIC_APPLICATION_IMPLEMENTED",
    "WORK_ITEM_STATUSES",
    "CoordinatorBindingError",
    "CoordinatorIdempotencyConflictError",
    "CoordinatorNotFoundError",
    "CoordinatorPersistenceFailureError",
    "CoordinatorRuntimeError",
    "CoordinatorStatus",
    "DispatchReport",
    "DispatchedWork",
    "FileBackedTaskMainCoordinatorStore",
    "MilestonePlanView",
    "PlanDriftError",
    "SessionRecoveryRequiredError",
    "StaleCoordinatorRevisionError",
    "TaskMainCoordinator",
    "TaskMainCoordinatorError",
    "TaskMainCoordinatorState",
    "TaskMainCoordinatorStore",
    "WorkItemCoordinatorStatus",
    "activate_milestone",
    "build_work_item_handoff_ref",
    "dispatch_identity_for",
    "evaluate_ready_work_items",
    "recover_coordinator",
]
