"""AF #57 M2/W1 — generated MAP.md / STATUS.md views.

    MAP.md     GENERATED=yes  AUTHORITY=no  PURPOSE=navigation
    STATUS.md  GENERATED=yes  AUTHORITY=no  PURPOSE=human/offline progress projection

Both views are deterministic renderings of the same Governance projection
semantics (the Cards).  They are never separately maintained, are never Plan
or progress authority, and are never read back as governance truth.  Physical
generation belongs to trusted Governance subsystem code; the agent-facing
workspace write path is not involved.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from aota_forge.governance.cards import (
    ArchitectureCard,
    GovernanceProjectionBundle,
    MilestoneCard,
    PlanCard,
    ProgressCard,
    ProjectCard,
)

MAP_AUTHORITY = False
STATUS_AUTHORITY = False
MAP_GENERATED = True
STATUS_GENERATED = True
MANUAL_MAP_PROGRESS_TRUTH = False
MANUAL_STATUS_PROGRESS_TRUTH = False
VIEWS_ARE_SOURCE_AUTHORITY = False

MAP_FILENAME = "MAP.md"
STATUS_FILENAME = "STATUS.md"

GENERATED_MARKER = (
    "<!-- GENERATED by the AF Governance Projection Engine (AF #57 M2/W1). "
    "AUTHORITY=no. Do not edit. -->"
)


def _completeness_line(complete: bool, missing: tuple[str, ...]) -> str:
    if complete:
        return "- complete: yes"
    return f"- complete: no (missing: {', '.join(missing)})"


def _render_project(lines: list[str], card: ProjectCard) -> None:
    lines.append("## Project")
    lines.append("")
    lines.append(f"- project_id: {card.project_id}")
    if card.project_ref:
        lines.append(f"- project_ref: {card.project_ref}")
    if card.project_status:
        lines.append(f"- project_status: {card.project_status}")
    lines.append(f"- plans: {card.plan_count}")
    for plan_ref in card.plan_refs:
        lines.append(f"  - plan: {plan_ref}")
    if card.governance_root_refs:
        lines.append(f"- governance_root_refs: {', '.join(card.governance_root_refs)}")
    lines.append(_completeness_line(card.complete, card.missing_facts))
    lines.append(f"- projection_id: {card.projection_id()}")
    lines.append("")


def _render_plans(lines: list[str], cards: tuple[PlanCard, ...]) -> None:
    lines.append("## Plans")
    lines.append("")
    if not cards:
        lines.append("- (none projected)")
        lines.append("")
        return
    for card in cards:
        lines.append(f"- plan: {card.plan_id}")
        if card.title:
            lines.append(f"  - title: {card.title}")
        if card.goal_summary:
            lines.append(f"  - goal: {card.goal_summary}")
        if card.lifecycle_state:
            lines.append(f"  - lifecycle: {card.lifecycle_state}")
        if card.plan_status:
            lines.append(f"  - plan_status: {card.plan_status}")
        if card.authority_ref:
            lines.append(f"  - authority: {card.authority_ref} ({card.authority_source_kind})")
        if card.current_milestone:
            lines.append(f"  - current_milestone: {card.current_milestone}")
        lines.append("  " + _completeness_line(card.complete, card.missing_facts)[2:])
        lines.append(f"  - projection_id: {card.projection_id()}")
    lines.append("")


def _render_milestones(lines: list[str], cards: tuple[MilestoneCard, ...]) -> None:
    lines.append("## Milestones")
    lines.append("")
    if not cards:
        lines.append("- (no current milestone projected)")
        lines.append("")
        return
    for card in cards:
        current = " (current)" if card.is_current else ""
        lines.append(f"- plan: {card.plan_id} / milestone: {card.milestone_id}{current}")
        if card.milestone_title:
            lines.append(f"  - title: {card.milestone_title}")
        if card.milestone_status:
            lines.append(f"  - status: {card.milestone_status}")
        if card.work_item_refs:
            lines.append(f"  - work_items: {', '.join(card.work_item_refs)}")
        if card.objective_summary:
            lines.append(f"  - objective: {card.objective_summary}")
        lines.append("  " + _completeness_line(card.complete, card.missing_facts)[2:])
        lines.append(f"  - projection_id: {card.projection_id()}")
    lines.append("")


def _render_architecture(lines: list[str], card: ArchitectureCard | None) -> None:
    lines.append("## Architecture")
    lines.append("")
    if card is None:
        lines.append("- (not projected)")
        lines.append("")
        return
    if card.baseline_id:
        lines.append(f"- baseline: {card.baseline_id}")
    if card.baseline_status:
        lines.append(f"- baseline_status: {card.baseline_status}")
    if card.accepted_ref:
        lines.append(f"- accepted_ref: {card.accepted_ref}")
    if card.plan_delta_ref:
        lines.append(f"- plan_delta_ref: {card.plan_delta_ref}")
    lines.append(_completeness_line(card.complete, card.missing_facts))
    lines.append(f"- projection_id: {card.projection_id()}")
    lines.append("")


def _render_navigation(lines: list[str], bundle: GovernanceProjectionBundle) -> None:
    lines.append("## Navigation refs")
    lines.append("")
    seen: set[tuple[str, str]] = set()
    for card in bundle.cards():
        for ref in card.navigation_refs:
            key = (ref.kind, ref.ref)
            if key in seen:
                continue
            seen.add(key)
            lines.append(f"- {ref.kind}: {ref.ref}")
    lines.append("")


def render_map_markdown(bundle: GovernanceProjectionBundle) -> str:
    """Deterministic MAP.md text: bounded navigation, never Plan authority."""
    if not isinstance(bundle, GovernanceProjectionBundle):
        raise TypeError("bundle must be a GovernanceProjectionBundle")
    lines: list[str] = [f"# MAP — {bundle.project.project_id}", "", GENERATED_MARKER, ""]
    _render_project(lines, bundle.project)
    _render_plans(lines, bundle.plans)
    _render_milestones(lines, bundle.milestones)
    _render_architecture(lines, bundle.architecture)
    _render_navigation(lines, bundle)
    return "\n".join(lines).rstrip("\n") + "\n"


def _render_progress(lines: list[str], card: ProgressCard | None) -> None:
    lines.append("## Progress (derived aggregate)")
    lines.append("")
    if card is None:
        lines.append("- (not projected)")
        lines.append("")
        return
    lines.append(f"- active_coordinator_count: {card.active_coordinator_count}")
    for fact in card.plan_lifecycle:
        lines.append(f"- plan_lifecycle: {fact.plan_id}={fact.lifecycle_state}")
    for fact in card.coordinator_facts:
        counts = ", ".join(f"{status}={count}" for status, count in fact.wi_status_counts)
        lines.append(
            f"- coordinator: {fact.coordinator_id} status={fact.status} milestone={fact.milestone_id}"
            + (f" wi_status=[{counts}]" if counts else "")
        )
    aggregate = card.execution_aggregate
    if aggregate is not None:
        states = ", ".join(f"{state}={count}" for state, count in aggregate.by_canonical_task_state)
        delivery = ", ".join(f"{state}={count}" for state, count in aggregate.by_delivery_state)
        lines.append(f"- executions: total={aggregate.total}" + (f" states=[{states}]" if states else ""))
        if delivery:
            lines.append(f"- execution_delivery: {delivery}")
        lines.append(
            f"- terminal_results: ok={aggregate.terminal_ok} failed={aggregate.terminal_failed}"
            f" requiring_recovery={aggregate.requiring_recovery}"
        )
    if card.open_blockers:
        for blocker in card.open_blockers:
            lines.append(f"- open_blocker: {blocker}")
    lines.append(
        "- human_brake: " + ("yes" if card.human_brake_active else "no" if card.human_brake_active is False else "unknown")
    )
    if card.next_action:
        lines.append(f"- next_action: {card.next_action}")
    if card.source_digest:
        lines.append(f"- source_digest: {card.source_digest}")
    lines.append(_completeness_line(card.complete, card.missing_facts))
    lines.append(f"- projection_id: {card.projection_id()}")
    lines.append("")


def render_status_markdown(bundle: GovernanceProjectionBundle) -> str:
    """Deterministic STATUS.md text: human/offline progress projection only."""
    if not isinstance(bundle, GovernanceProjectionBundle):
        raise TypeError("bundle must be a GovernanceProjectionBundle")
    lines: list[str] = [f"# STATUS — {bundle.project.project_id}", "", GENERATED_MARKER, ""]
    _render_progress(lines, bundle.progress)
    lines.append("## Projection")
    lines.append("")
    lines.append(f"- bundle_projection_digest: {bundle.projection_digest()}")
    lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


@dataclass(frozen=True)
class GeneratedViews:
    """Deterministic generated view texts for one projection bundle."""

    map_markdown: str
    status_markdown: str

    def to_dict(self) -> dict[str, Any]:
        return {"map_markdown": self.map_markdown, "status_markdown": self.status_markdown}


def generate_views(bundle: GovernanceProjectionBundle) -> GeneratedViews:
    return GeneratedViews(
        map_markdown=render_map_markdown(bundle),
        status_markdown=render_status_markdown(bundle),
    )


def write_generated_views(project_directory: str | Path, bundle: GovernanceProjectionBundle) -> tuple[Path, Path]:
    """Write MAP.md / STATUS.md into a trusted governance project directory.

    Disposable local-governance materialization only: this function is called
    by trusted Governance subsystem code with an explicit caller-supplied
    directory.  It never mutates the truth stores and creates no authority.
    """
    if isinstance(project_directory, (str, Path)) and str(project_directory).strip():
        target = Path(project_directory)
    else:
        raise TypeError("project_directory must be a non-empty path")
    views = generate_views(bundle)
    target.mkdir(parents=True, exist_ok=True)
    map_path = target / MAP_FILENAME
    status_path = target / STATUS_FILENAME
    map_path.write_text(views.map_markdown, encoding="utf-8")
    status_path.write_text(views.status_markdown, encoding="utf-8")
    return map_path, status_path


__all__ = [
    "GENERATED_MARKER",
    "MANUAL_MAP_PROGRESS_TRUTH",
    "MANUAL_STATUS_PROGRESS_TRUTH",
    "MAP_AUTHORITY",
    "MAP_FILENAME",
    "MAP_GENERATED",
    "STATUS_AUTHORITY",
    "STATUS_FILENAME",
    "STATUS_GENERATED",
    "VIEWS_ARE_SOURCE_AUTHORITY",
    "GeneratedViews",
    "generate_views",
    "render_map_markdown",
    "render_status_markdown",
    "write_generated_views",
]
