"""M3-B11 isolated non-authoritative shadow module (Issue #9, lane M3-B11).

Provides:
- Explicit ShadowNamespace model
- Isolated ShadowRepository and InMemoryShadowRepository
- Atomic ShadowTransaction boundary
- Deterministic ShadowSnapshot representation
"""

from __future__ import annotations

from aota_forge.core.shadow.model import (
    B11_CANONICAL_GRAPH_WRITE_COUNT,
    B11_PRODUCTION_REPOSITORY_WRITE_COUNT,
    B11_SHADOW_IMPORT_MAY_ADVANCE_PRODUCTION_SUBJECT_REVISION,
    B11_SHADOW_IMPORT_MAY_CONSUME_PRODUCTION_LEASE,
    B11_SHADOW_IMPORT_MAY_MUTATE_CURRENT_BINDING,
    B11_SHADOW_IMPORT_REQUIRES_PRODUCTION_CAPABILITY_LEASE,
    CANONICAL_SUBJECT_REVISION_REMAINS_B6_AUTHORITY,
    FORBIDDEN_PRODUCTION_NAMESPACES,
    PRODUCTION_LEASE_CONSUMPTION_COUNT,
    SHADOW_NAMESPACE_DEFAULTS_TO_PRODUCTION,
    SHADOW_NAMESPACE_EXPLICIT,
    SHADOW_REPOSITORY_ALIASES_PRODUCTION_REPOSITORY,
    SHADOW_REPOSITORY_IS_PRODUCTION_AUTHORITY,
    SHADOW_REVISION_IS_CANONICAL_REVISION_AUTHORITY,
    SHADOW_STATE_VISIBLE_TO_PRODUCTION_BINDING_BY_DEFAULT,
    ShadowNamespace,
    ShadowStateMetadata,
)
from aota_forge.core.shadow.repository import (
    InMemoryShadowRepository,
    ShadowRepository,
)
from aota_forge.core.shadow.snapshot import (
    SHADOW_SNAPSHOT_DETERMINISTIC,
    SHADOW_SNAPSHOT_IS_PRODUCTION_AUTHORITY,
    SHADOW_SNAPSHOT_IS_SUBJECT_AUTHORITY,
    ShadowSnapshot,
)
from aota_forge.core.shadow.transaction import (
    B11_PARTIAL_SHADOW_COMMIT_ALLOWED,
    FAILED_SHADOW_IMPORT_LEAVES_PARTIAL_COMMIT,
    ShadowTransaction,
    ShadowTransactionError,
    ShadowTransactionResult,
)

__all__ = [
    "SHADOW_REPOSITORY_IS_PRODUCTION_AUTHORITY",
    "SHADOW_REPOSITORY_ALIASES_PRODUCTION_REPOSITORY",
    "SHADOW_NAMESPACE_DEFAULTS_TO_PRODUCTION",
    "SHADOW_NAMESPACE_EXPLICIT",
    "SHADOW_STATE_VISIBLE_TO_PRODUCTION_BINDING_BY_DEFAULT",
    "SHADOW_REVISION_IS_CANONICAL_REVISION_AUTHORITY",
    "CANONICAL_SUBJECT_REVISION_REMAINS_B6_AUTHORITY",
    "B11_CANONICAL_GRAPH_WRITE_COUNT",
    "B11_PRODUCTION_REPOSITORY_WRITE_COUNT",
    "PRODUCTION_LEASE_CONSUMPTION_COUNT",
    "B11_SHADOW_IMPORT_MAY_ADVANCE_PRODUCTION_SUBJECT_REVISION",
    "B11_SHADOW_IMPORT_REQUIRES_PRODUCTION_CAPABILITY_LEASE",
    "B11_SHADOW_IMPORT_MAY_CONSUME_PRODUCTION_LEASE",
    "B11_SHADOW_IMPORT_MAY_MUTATE_CURRENT_BINDING",
    "FORBIDDEN_PRODUCTION_NAMESPACES",
    "ShadowNamespace",
    "ShadowStateMetadata",
    "ShadowRepository",
    "InMemoryShadowRepository",
    "SHADOW_SNAPSHOT_DETERMINISTIC",
    "SHADOW_SNAPSHOT_IS_PRODUCTION_AUTHORITY",
    "SHADOW_SNAPSHOT_IS_SUBJECT_AUTHORITY",
    "ShadowSnapshot",
    "B11_PARTIAL_SHADOW_COMMIT_ALLOWED",
    "FAILED_SHADOW_IMPORT_LEAVES_PARTIAL_COMMIT",
    "ShadowTransaction",
    "ShadowTransactionError",
    "ShadowTransactionResult",
]
